### ISSUE TITLE
Error while indexing

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/booster-catalog-service#10]
```
INFO: Indexing /home/ggastald/workspace/launchpad/booster-catalog-service/target/booster-catalog6741109803711849079/health-check/vert.x/community/vertx-health-check-community-booster.yaml ...
Sep 11, 2017 11:02:51 AM io.openshift.booster.catalog.spi.NativeGitBoosterCatalogPathProvider createBoosterContentPath
INFO: Executing: git clone https://github.com/openshiftio-vertx-boosters/vertx-health-checks-booster --branch master --recursive --depth=1 /home/ggastald/workspace/launchpad/booster-catalog-service/target/booster-catalog6741109803711849079/.boosters/vertx-health-check-community-booster
Sep 11, 2017 11:02:53 AM io.openshift.booster.catalog.spi.NativeGitBoosterCatalogPathProvider createBoosterContentPath
INFO: Executing: git checkout master --quiet
Sep 11, 2017 11:02:53 AM io.openshift.booster.catalog.BoosterCatalogService indexBooster
SEVERE: Error while reading metadata from /home/ggastald/workspace/launchpad/booster-catalog-service/target/booster-catalog6741109803711849079/health-check/vert.x/community/vertx-health-check-community-booster.yaml
mapping values are not allowed here
 in 'reader', line 3, column 7:
      - id: community
          ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:465)
	at io.openshift.booster.catalog.BoosterCatalogService.indexBooster(BoosterCatalogService.java:259)
	at io.openshift.booster.catalog.BoosterCatalogService.access$000(BoosterCatalogService.java:57)
	at io.openshift.booster.catalog.BoosterCatalogService$1.visitFile(BoosterCatalogService.java:148)
	at io.openshift.booster.catalog.BoosterCatalogService$1.visitFile(BoosterCatalogService.java:133)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at io.openshift.booster.catalog.BoosterCatalogService.indexBoosters(BoosterCatalogService.java:132)
	at io.openshift.booster.catalog.BoosterCatalogService.doIndex(BoosterCatalogService.java:111)
	at io.openshift.booster.catalog.BoosterCatalogService.lambda$index$0(BoosterCatalogService.java:97)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by gastaldi** [comment]
Caused by malformed YAML: https://github.com/openshiftio-vertx-boosters/vertx-health-checks-booster/pull/10

Closing
